name: SuperLobby
version: 4.4.8
main: com.pedrojm96.superlobby.SuperLobby
author: PedroJM96
description: Customize many functions and features of the server lobby in a powerful and free for all.
api-version: 1.13
softdepend: [PlaceholderAPI,Vault,PlayerPoints,ViaVersion,ProtocolLib]